import { Header } from '@/components/header/Header'
import { SideBar } from '@/components/sidebar/SideBar'
import { useLoadExportedMethods } from '@/hooks/useLoadExportedMethods'
import { useSetSideBar } from '@/state/sidebar'
import { Main } from '@/views/Main'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'

const index = () => {
  useLoadExportedMethods()
  const setView = useSetSideBar()
  const router = useRouter()
  const { view } = router.query

  useEffect(() => {
    if (view) {
      setView(view)
    }
  }, [view])

  return (
    <>
      <Head>
        <title>Home | NX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nx/logo.svg" />
      </Head>
      <>
        <Header />

        <div className="docs not__full">
          <SideBar />
          <div className="docs__content">
            <Main />
          </div>
        </div>
      </>
    </>
  )
}

export default index
